### ISSUE TITLE
transpose_sinking pass

### ISSUE THREAD

**Issue by lisa0314** [openvinotoolkit/openvino_tensorflow#102]
I find it will crash when I use transpose_sinking pass through a ngraph function which only have one Conv op and two inserted transpose op which is used to handle the nhwc input and output. I suppose it should do nothing in this situation instead of crash.

**Comment by cavusmustafa** [comment]
Hi @lisa0314, thank you for catching this. We will be looking into the issue. Also, it would be great if you can share the model (frozen .pb file or saved model), the script to reproduce the error, and the output logs. Thanks.

**Comment by lisa0314** [comment]
@cavusmustafa thanks for your kind reply. I have found the root cause for my case and it's not the issue of transpose_sinking algorithm. I will close this issue.
