### ISSUE TITLE
Incompatible TF and OV packages

### ISSUE THREAD

**Issue by niluwin-intel** [openvinotoolkit/openvino_tensorflow#118]
I am trying to install Openvino_tensorflow library but facing incompatible TF library issue

Code sample:
import tensorflow as tf
print('TensorFlow version: ',tf.__version__)
import openvino_tensorflow
print(openvino_tensorflow.__version__)

Error:

TensorFlow version:  2.4.1
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    import openvino_tensorflow
  File "/home/nuc2/.local/lib/python3.6/site-packages/openvino_tensorflow/__init__.py", line 97, in <module>
    .format(TF_VERSION, TF_VERSION_NEEDED))
ValueError: Error: Installed TensorFlow version 2.4.1
 openvino_tensorflow built with: 2.2.2

Steps used for installation in a conda environment:
pip3 install -U pip==21.0.1
pip3 install -U tensorflow==2.4.1
pip3 install openvino-tensorflow

**Comment by ck-intel** [comment]
Could you try "pip3 install -U openvino-tensorflow"  or "pip3 install --force-reinstall openvino-tensorflow"? Looks like you already have an older ovtf package which was built with TF-2.2.2 and "pip3 install openvino-tensorflow" would not install the new package if you already have the package installed. 
We will upgrade the instructions!
