### ISSUE TITLE
TF2.3.1 supported?

### ISSUE THREAD

**Issue by rickyxume** [openvinotoolkit/openvino_tensorflow#154]
Is there a specific Tensorflow version required? Here, I meet a question that my other AI components don't work well when developing projects, they only support up to Tensorflow 2.3.1, but I'd love to accelerate with openvino. Is there a way to speed it up? I would appreciate it if possible.

**Comment by ck-intel** [comment]
The released pypi package supports TensorFlow - 2.4.1. However you can build OpenVINO-TensorFlow from source with TF-2.3.1  or any other 2.x version. Please follow the build from source instructions mentioned here: https://github.com/openvinotoolkit/openvino_tensorflow/blob/master/docs/BUILD.md#build-from-source
