### ISSUE TITLE
Issues with convert_yolov3 in aditya/upgrade_samples branch

### ISSUE THREAD

**Issue by vibhubithar** [openvinotoolkit/openvino_tensorflow#160]
Connecting to pjreddie.com (pjreddie.com)|128.208.4.108|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 248007048 (237M) [application/octet-stream]
Saving to: ‘weights/yolov3.weights’

weights/yolov3.weights        100%[=================================================>] 236.52M  40.8MB/s    in 6.9s

2021-09-03 10:17:16 (34.3 MB/s) - ‘weights/yolov3.weights’ saved [248007048/248007048]

./convert_yolov3.sh: line 17: python: command not found
./convert_yolov3.sh: line 18: python: command not found
cp: cannot stat 'weights/yolo_v3_darknet_2.pb': No such file or directory
cp: cannot stat 'weights/darknet53.h5': No such file or directory

**Comment by ck-intel** [comment]
@adisan3 Can you take a look into this issue?

**Comment by adisan3** [comment]
Hi @vibhubithar , thanks for catching this. After looking at the issue, found that the script is unable to resolve the python version. This issue should be resolved with  #157.  Could you please confirm if it is resolved in your side so we can close this issue? Thank you.
