### ISSUE TITLE
Incorrect tensorflow version mentioned in readme

### ISSUE THREAD

**Issue by vibhubithar** [openvinotoolkit/openvino_tensorflow#161]
Readme suggests "pip3 install -U tensorflow==2.5.0" when running the sample code it fails and says OVTF built with 2.4.1

**Comment by ck-intel** [comment]
Right, as the current publicly released wheel is built with TensorFlow 2.4.1.  With the upcoming OpenVINO-Tensorflow release, the TensorFlow version will be upgraded, and the Readme is being updated for it (WIP). Please refer the documentation for tagged release 0.5.0 for now: https://github.com/openvinotoolkit/openvino_tensorflow/tree/v0.5.0
