### ISSUE TITLE
How to install tf 1.15.2 version ovtf?

### ISSUE THREAD

**Issue by violet17** [openvinotoolkit/openvino_tensorflow#209]

**Comment by sspintel** [comment]
Hi @violet17 

You can build OpenVINO integration with TensorFlow from source with any TensorFlow version. Please check out the build documentation for more details. https://github.com/openvinotoolkit/openvino_tensorflow/blob/master/docs/BUILD.md

You could try something like

`python3 build_ovtf.py --tf_version=v1.15.2`

**Comment by violet17** [comment]
@sspintel  Thank you very much. It would be better that if the wheel is provided.

**Comment by violet17** [comment]
Wheel for tf 1.15.2, openvino 2021.4.582, python 3.6
need to unzip
[openvino_tensorflow-1.0.1-cp36-cp36m-manylinux2014_x86_64.whl.zip](https://github.com/openvinotoolkit/openvino_tensorflow/files/7535529/openvino_tensorflow-1.0.1-cp36-cp36m-manylinux2014_x86_64.whl.zip)
