### ISSUE TITLE
Entry Point not Found 

### ISSUE THREAD

**Issue by terryll** [openvinotoolkit/openvino_tensorflow#326]
After installing openvino_tensorflow, the message "Entry Point not Found" shows up on the command
python "import openvino_tensorflow as ovtf" 
![Screenshot 2022-07-04 230310](https://user-images.githubusercontent.com/18722895/177241299-8f0b321b-05f9-4883-b7dc-c464a1c1c0d0.jpg)

Installation:
python 3.9,windows10
install with to 
  pip3 install -U pip
  pip3 install tensorflow==2.8.0
  pip3 install openvino-tensorflow==2.0.0

Test under python:
   import openvino_tensorflow
   See image for error message

Did I missed something simple?

**Comment by ck-intel** [comment]
@terryll TensorFlow wheel for Windows from PyPi does't have all the API symbols enabled which are required for OpenVINO™ integration with TensorFlow. User needs to install the TensorFlow wheel from the assets of our Github release page.
Pls follow the installation instructions as described in this link: https://github.com/openvinotoolkit/openvino_tensorflow/blob/master/docs/INSTALL.md#12-install-openvino-integration-with-tensorflow-alongside-tensorflow-released-on-github-works-on-windows

**Comment by terryll** [comment]
Thanks, I did missed the instruction.
On another question, since I'm not familiar with Linus, What does the following do?
!chmod +x convert_yolov4.sh && bash convert_yolov4.sh
Is there a Windows 10 equivalent?

**Comment by ck-intel** [comment]
Yes, there is a windows equivalent for it: convert_yolov4.bat
Please follow "For Windows" section of the examples readme: https://github.com/openvinotoolkit/openvino_tensorflow/tree/master/examples#python-implementation-for-object-detection

**Comment by terryll** [comment]
Thanks a lot.  
I reinstall again and  follow the installation steps closely this time and was able to run the sample object decoction sample.  One additional question  is the processing time.
The processing time is over 520ms on  MYRIAD mode. It's a lot longer than I expected.  With MYRIAD at 416x416, I normally get 80ms with ssd_milbileV2.

I try adding the line : F_ENABLE_ONEDNN_OPTS=1 in the program. The result did not change much.

Any thoughts on the processing time ?
Thanks,
Terry

 

 

Environments: Windows 10, Conda, openvino_2022.1.0

**Comment by ck-intel** [comment]
If your model is TF2 based, then pls try setting following environment variable too, which may provide further improvement: 
OPENVINO_TF_CONVERT_VARIABLES_TO_CONSTANTS=1  (for detailed info about it refer: https://github.com/openvinotoolkit/openvino_tensorflow/blob/ck/fix_const_op_translation/docs/USAGE.md#environment-variables).  As you have seen in the sample, the first initial runs takes longer time, so try measuring timing after couple of warm up iterations. 
However performance improvement of SSD & Faster-RCNN object detection models are in progress and will be addressed in the upcoming releases.

**Comment by terryll** [comment]
Thanks, since my application will not work with python 3.9 at this time.  I will put this method a hold for now.
