### ISSUE TITLE
Slower performance than tf

### ISSUE THREAD

**Issue by jams01** [openvinotoolkit/openvino_tensorflow#331]
Hi, I'm trying to use openvino_tensorflow on my core i7-6700 CPU but if I use openvino tensorflow is around 10x slower than using only tf.
OS : ubuntu 20.04
CPU: core i7-6700

I just installed openvino_tensorflow and if I run my code using only TF I got an inference time of 0.10 s.
Then I add the line
 
`
import openvino_tensorflow
openvino_tensorflow.set_backend('CPU')`

My inference time is 1.5 s, log says
`2022-07-11 09:50:48.690843: OVTF Summary -> 90 out of 624 nodes in the graph (14%) are now running with OpenVINO™ backend`

**Comment by jams01** [comment]
I'm running these models on a loop, the first iterations are way slower in both scenarios, but after a few iterations, I got these measures. I have run up to 400 iters and no changes.

Does the CPU generation matters? Should I also test in a newer CPU?

I will try to create a test code, and if you could help, that will be amazing.

**Comment by sspintel** [comment]
Sometimes a newer-gen CPU might help. You could try them out on [Intel DevCloud](https://www.intel.com/content/www/us/en/developer/tools/devcloud/overview.html)

Please also try enabling the envvar `OPENVINO_TF_CONVERT_VARIABLES_TO_CONSTANTS` 

You can find its description and other such useful envvars here: https://github.com/openvinotoolkit/openvino_tensorflow/blob/master/docs/USAGE.md

**Comment by jams01** [comment]
Great!, it worked! the envvar solved the problem

Thank you so much

Execution time: 0.01780414581298828 seconds retina
Execution time: 0.026752471923828125 seconds Vgg
