### ISSUE TITLE
ERROR: tensorflow-2.9.1-cp39-cp39-win_amd64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by davemaster** [openvinotoolkit/openvino_tensorflow#344]
Greetings, 

When I tried to install openvino_tensorlow, the following error came out:

**ERROR: tensorflow-2.9.1-cp39-cp39-win_amd64.whl is not a supported wheel on this platform.**

Any clue? Thanks in advance

my system:

windows 10
python 3.8, in the venv Im trying to install
pip command: pip install 

I try changing 3.8 with 3.9, NOTHING....

Had anyone installed openvino_tensorflow in Windows 10 x64?

Thanks in advance

**Comment by davemaster** [comment]
finally, it seems work, using conda, so, python venv doesn't work 

![imagen](https://user-images.githubusercontent.com/1075807/180661833-85041856-9eed-4c0b-9ef6-ed641861ef37.png)

**Comment by ck-intel** [comment]
Currently openvino-tensorflow supports only Python 3.9 on Windows and python venv also works.
Please follow the installation instructions given here:  https://github.com/openvinotoolkit/openvino_tensorflow/blob/master/docs/INSTALL.md#windows

**Comment by davemaster** [comment]
conda python 3.9 and python 3.9 global are in conflict, or something like that. So, solution, uninstall conda, python 3.9, then install python 3.9 for all users, and add location to PATH
