### ISSUE TITLE
Unable to see .pb file

### ISSUE THREAD

**Issue by Swazir9449** [openvinotoolkit/openvino_tensorflow#346]
![Error1](https://user-images.githubusercontent.com/60838656/181272746-6c97201d-bfb1-43f0-bcc3-c039771d1e49.JPG)
![error2](https://user-images.githubusercontent.com/60838656/181272754-b6041363-bcf4-425b-ad88-85a395baa6f4.JPG)
![error3](https://user-images.githubusercontent.com/60838656/181272760-7d9d80b8-5602-4ea5-a090-51381f808ef8.JPG)

**Comment by Swazir9449** [comment]
Not sure why python is unable to see the file. I have checked to make sure I am in the correct directory.

**Comment by ck-intel** [comment]
Looks like this issue is not related with "OpenVINO integration with TensorFlow".  I guess the issue is related to OpenVINO, and it has separate github page, please post it there.
