### ISSUE TITLE
set_backend interface problem

### ISSUE THREAD

**Issue by AlexKoff88** [openvinotoolkit/openvino_tensorflow#63]
Can we consider renaming `set_backend` to `set_device`? This change will make this interface consistent with what TF and PT have and avoid confusion:
- https://www.tensorflow.org/api_docs/python/tf/device
- https://pytorch.org/docs/stable/tensors.html#torch.Tensor.to

OpenVINO is already a backend for TF and calling `set_backend` for it looks really confusing.

**Comment by suryasidd** [comment]
Thank you for the suggestion. We will evaluate this. We may register OpenVINO as a device into TensorFlow in future and then the hardware on which inference is run on can be set using set_backend method. Hence we selected set_backend instead of set_device.
